### ISSUE TITLE
Use workspaces to organize virtual packages structure

### ISSUE THREAD

**Issue by ir4y** [beda-software/fhir-client-testing-tool#7]
For example here should be import from validator package https://github.com/beda-software/fhir-client-testing-tool/blob/main/src/suites/1.0.0-ballot/patients.spec.ts#L5 instead of relative import.

Check https://github.com/medplum/medplum as a reference

**Comment by projkov** [comment]
Now all independent modules are stored in the packages/*

**Comment by ir4y** [comment]
We need the following packages structure:
- test-server -  it is a main package that contain API (NestJs app)
- [fhir-validator](https://github.com/beda-software/fhir-client-testing-tool/tree/main/packages/fhir-validator)
- Test suite that uses DB access
- Test suite (first version)
- Utils (all the code that is shared across at least any 2 of defined above packages)

**Comment by projkov** [comment]
Try to use tests without export

**Comment by projkov** [comment]
Remove helpers

**Comment by projkov** [comment]
await isResourceValid(request.requestBody as Patient))

Use guard

**Comment by projkov** [comment]
function checkAvailableParams(availableParams: string[], combo: boolean, requests: Request[])

check set and superset
